[snowflake]
user = "EXAMPLE_USER"
account = "example-0000000"
# Use an authenticator if you are using your e-mail as the ``user`` for SSO
authenticator = "externalbrowser"
# Additionally, if you are using a service account with a traditional
# username and password, you can use ``password`` in place of the authenticator:
# password = "EXAMPLE_PASSWORD"
